### PR TITLE
AttributeError: module 'spikeextractors' has no attribute 'sorting_exporter_dict'

### PR DESCRIPTION
**Pull request by lwty**
'sorting_exporter_dict' should be changed to 'sorting_extractor_dict'

### CODE REVIEW

**Comment by colehurwitz** [comment]
Hi @iwty, thanks for your interest in spikely. Which version of spikeinterface are you using by chance? Currently, spikely only supports 'spikeextractors==0.7.0', 'spikesorters==0.2.0', and 'spiketoolkit==0.5.2'. This error seems like it could be stemming from this requirement mismatch.

We plan to release a new version of spikely hopefully by the end of this week that is up-to-date with the latest branch of spikeinteface as well.

**Comment by lwty** [comment]
Hi Cole,

The versions are as follows:

spikeinterface: 0.9.9
spikeextractors: 0.8.4
spikesorters: 0.3.3
spiketoolkit: 0.6.3

Thanks for your reply. I will wait for the new version.

Best regards,
Tianyu

**Comment by lwty** [comment]
Hi Cole,

Are there any updates? Thanks a lot!

Best regards,
Tianyu

**Comment by colehurwitz** [comment]
Hi Tianyu, sorry for the delay. We are working to finish this week. We are making progress in another branch, but it is taking slightly longer than we expected. Will let you know!

**Comment by lwty** [comment]
Thanks Cole!
So gratitude for your effort.

**Comment by colehurwitz** [comment]
Hi Tianyu (@lwty ), 

Again, sorry for the delay. We just merged a new version of spikely into the master branch and will be releasing a pypi version soon. It should solve the issue you ran into as it is fully up-to-date with SpikeInterface. Please let us know if you run into any issues.

**Pull request closed without merging**
